name: build arch iso for unattended installation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:latest
      options: --privileged
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: find .
      - run: cat /etc/os-release
      - run: pacman-key --init
      - run: pacman --noconfirm -Sy archlinux-keyring
      - run: bash buildiso.sh
      - uses: actions/upload-artifact@v4
        with:
          name: unattended arch installation iso
          path: /tmp/auto-ins/out/*.iso
      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: /tmp/auto-ins/out/*.iso
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
